### PR TITLE
Game v2

### PR DESCRIPTION
**Pull request by Haseebullah9012**
The Version 2 of the Game.

### CODE REVIEW

**Comment by Haseebullah9012** [comment]
Merge the Pull Request @ArmaghanBz. 
It is now looking Great. :100:

**Review by ArmaghanBz — COMMENTED** [review]
Really Acknowledge this brother

**Comment by ArmaghanBz** [comment]
This is great brother. Hope we work on more code of mine, as I'm learning from my mistakes and hope to get better and better in coming future

**Comment by Haseebullah9012** [comment]
Yeah of course! :+1: 
I am also Learning Software Development. And also learning How to use Git and GitHub. :trophy: 
And as you can see from the Commits and their Title/Description, I am trying to behave Professionally. :laughing: 

> This is great brother. Hope we work on more code of mine, as I'm learning from my mistakes and hope to get better and better in coming future

**Comment by ArmaghanBz** [comment]
Yes, I can see that. btw I'm learning it too.

**Pull request merged**
